// ...existing code...
const userSchema = new Schema({
  // ...existing code...
  email: { type: String, required: true, unique: true },
  // ...existing code...
  receiveUpdates: { type: Boolean, default: false },
  // ...existing code...
});
// ...existing code...

